### ISSUE TITLE
How to evaluate results on the test set?

### ISSUE THREAD

**Issue by ShaelynW** [tjubiit/TJU-DHD#1]
Hi!
How can I evaluate results on the test set?

**Comment by JialeCao001** [comment]
@ShaelynW Thanks for interest. You can send your results to us.

**Comment by ShaelynW** [comment]
OK! Can you leave an email address?

**Comment by JialeCao001** [comment]
You can send it to me. connor@tju.edu.cn

**Comment by ShaelynW** [comment]
Thanks!
