### ISSUE TITLE
password to download data with BaiduNetDisk

### ISSUE THREAD

**Issue by qingzi02010** [tjubiit/TJU-DHD#3]
I didn't find the password when downloading data with BaiduNetDisk. Is it available? Thanks.

**Comment by Hanqing-Sun** [comment]
Thanks for using our dataset and reading the intro.
Codes (passwords) are provided after each "BaiduNetDisk" link in the parentheses, e.g., `BaiduNetDisk (code: biit)`.

PS: All codes are set as `biit`.
