### ISSUE TITLE
How to evaluate the TJU-DHD-pedestrian test set?

### ISSUE THREAD

**Issue by GipinLinn** [tjubiit/TJU-DHD#4]
Due to the lack of test set's annotation, I have a problem that how to evaluate the test set of TJU-DHD-pedestrian dataset?

**Comment by JialeCao001** [comment]
@GipinLinn You can conduct ablation study on validation. If you want evaluate test set, you can send the json file to us.

**Comment by GipinLinn** [comment]
OK,  Thank you.

**Comment by GipinLinn** [comment]
There is a question that whether the miss rate of the validation set is higher than the miss rate of the test set. Because the paper hasn't depicted the miss rate on the validation set.
I have tested the validation set on Adapted Faster r-CNN and then the miss rate is more than 30%.

**Comment by JialeCao001** [comment]
@GipinLinn The results reported in the paper are tested on validation set.

**Comment by GipinLinn** [comment]
okay, Thanks.

**Comment by GipinLinn** [comment]
您好，您的邮件我已收到，谢谢，祝你生活愉快，天天开心！
