### ISSUE TITLE
The size of inputs when training and testing?

### ISSUE THREAD

**Issue by Yorionice1** [tjubiit/TJU-DHD#6]
In your paper, the size of the input image is set to (1333,800), but the setting doesn't match the ratio of the original image. Should we keep the ratio when training and testing.

**Comment by Yorionice1** [comment]
And could you share details of the experiment settings, thank you.

**Comment by JialeCao001** [comment]
Thanks for interest. We keep the ratio of the image during both training and testing. We set (1333, 8000) for object detection and (2048, 1024) for pedestrian detection. Please note that (1333, 800) does not mean an accurate size. Usually, we keep the short edge as 800 and the long edge as no more than 1333. When the long edge is more than 1333, we will keep the long edge as 1333 and keep the short edge as less than 800.
I am sorry that the original configs are not kept. I remember that we keep most default settings of the method in mmdetection. The only thing is that we add ignored regions. I think it is easy to get the performance of the paper reported.

**Comment by Yorionice1** [comment]
Thank you.
