### ISSUE TITLE
md5sum for released datasets and backup links not working

### ISSUE THREAD

**Issue by manisoftwartist** [tjubiit/TJU-DHD#7]
Hi, 
1. Would it be possible for you to release the md5 hash for all the released zip files please?
2. None of the links named backup are working (for example, http://vi.tju.edu.cn/public/dhd_dataset/dhd_campus_train_images.zip.001)

**Comment by Hanqing-Sun** [comment]
Thank you for your interest in our work.

1. We updated the [readme](https://github.com/tjubiit/TJU-DHD/blob/master/README.md) file to provide md5 checksums. You can find them below each file link.
2. Our backup server is currently not available and we are working on that. The backup links are temporarily commented out to avoid misguidance. It will be added back as soon as the server is online again.
